language: generic
sudo: required
services:
  - docker:

before_install:
  - docker build -t imcool2551/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true imcool2551/docker-react npm run test
